# Generated by Django 6.0.5 on 2026-05-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
