# Generated by Django 6.0.5 on 2026-05-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_service_areas'),
        ('inventory', '0006_servicearea_order_customer_phone_and_more'),
    ]

    operations = [
    ]
